/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#785a1a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c8c6c5",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#928265",
        "on-surface-variant": "#444748",
        "on-secondary-fixed": "#261900",
        "background": "#f9f9f9",
        "surface-tint": "#5f5e5e",
        "on-tertiary-fixed": "#241a06",
        "primary-container": "#1c1b1b",
        "tertiary-container": "#241a06",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#52452c",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#d7c4a4",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary": "#000000",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c7c7",
        "secondary-fixed": "#ffdea5",
        "tertiary-fixed": "#f4e0be",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "surface-dim": "#dadada",
        "inverse-primary": "#c8c6c5",
        "secondary-fixed-dim": "#e9c176",
        "secondary": "#775a19",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container": "#eeeeee",
        "inverse-surface": "#2f3131",
        "secondary-container": "#fed488",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed": "#1c1b1b",
        "surface-variant": "#e2e2e2",
        "on-primary-container": "#858383",
        "on-error": "#ffffff",
        "outline": "#747878",
        "on-primary-fixed-variant": "#474646",
        "primary-fixed": "#e5e2e1",
        "on-surface": "#1a1c1c",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
