package com.theatelier.backend.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class VerifyPaymentRequest {

    /**
     * Our internal order ID (links Razorpay payment back to our DB order)
     */
    @NotNull(message = "Order ID is required")
    private Long orderId;

    /**
     * Razorpay order ID returned when creating the order (e.g. order_XXXXXXXX)
     */
    @NotBlank(message = "Razorpay Order ID is required")
    private String razorpayOrderId;

    /**
     * Razorpay payment ID returned after successful payment (e.g. pay_XXXXXXXX)
     */
    @NotBlank(message = "Razorpay Payment ID is required")
    private String razorpayPaymentId;

    /**
     * HMAC-SHA256 signature generated by Razorpay on the client side
     */
    @NotBlank(message = "Razorpay signature is required")
    private String razorpaySignature;
}
